### ISSUE TITLE
Constant timeout errors.

### ISSUE THREAD

**Issue by justinbadal** [pinkpixel-dev/deep-research-mcp#1]
Hello!

I am yet to run the tool successfully with a request. I am using it through LibreChat. I get persistent timeout errors. 

What can I provide you that would be most helpful?

**Comment by sizzlebop** [comment]
If you have any error messages or logs please share them. I will look into this asap.

**Comment by justinbadal** [comment]
I'm sorry this isn't super helpful. I'm at my day job right now and I can't pull my logs. 

However, I did some testing after sending that initial message. 

First, I am using LibreChat and increased the MCP timeout to a very large number to allow more time for the MCP to do it's thing. This resulted in an extremely large context that Claude couldn't process, but gpt-4.1 could. 

I then sent another prompt stating that the timeouts should be increased from 180 to 240. This got passed through successfully, but the crawl timeout didn't increase, only the search timeout. 

I guess my takeaway from this is ...

Would it be able to have environment variables we can pass through in our MCP command (YAML in the case of LibreChat) to specify the limits? Number of searches, timeout for searching, timeout for crawling? Instead of relying on the LLM to do it or the user to provide it in the prompt.

**Comment by sizzlebop** [comment]
## 🎉 Issue Resolved!

I've implemented a comprehensive fix for the timeout issues you're experiencing in LibreChat. The solution adds **environment variable support** for timeout and performance configuration, which is exactly what you requested!

### ✅ **What's Fixed**

**New Environment Variables Added:**
- `SEARCH_TIMEOUT` - Configure search request timeouts (default: 60s)
- `CRAWL_TIMEOUT` - Configure crawl request timeouts (default: 180s) 
- `MAX_SEARCH_RESULTS` - Set maximum search results (default: 7)
- `CRAWL_MAX_DEPTH` - Set maximum crawl depth (default: 1)
- `CRAWL_LIMIT` - Set maximum URLs to crawl per source (default: 10)

### 🔧 **How to Use in LibreChat**

Update your MCP configuration YAML to include these environment variables:

```yaml
env:
  TAVILY_API_KEY: "tvly-YOUR_API_KEY"
  SEARCH_TIMEOUT: "240"     # 4 minutes for search
  CRAWL_TIMEOUT: "600"      # 10 minutes for crawl
  MAX_SEARCH_RESULTS: "5"   # Fewer results = faster processing
  CRAWL_MAX_DEPTH: "1"      # Limit crawl depth
  CRAWL_LIMIT: "8"          # Limit URLs per source
```

### 📈 **Precedence Order**
1. **Tool arguments** (if LLM provides them in the request)
2. **Environment variables** (your YAML config) ← **This is what you wanted!**
3. **Default values** (fallback)

### 🚀 **Additional Optimizations Already Present**

I also confirmed the tool already includes several performance optimizations:
- ✅ Memory tracking and automatic garbage collection
- ✅ Hardware acceleration support (WebGPU)
- ✅ Progress tracking for long operations
- ✅ Resource limits to prevent excessive memory usage
- ✅ Domain validation to focus crawling

### 📦 **Version 1.2.1 Released**

This fix is available in version **1.2.1** which includes:
- Environment variable timeout configuration
- Enhanced startup logging showing your current settings
- Updated documentation and examples
- Improved LibreChat compatibility

### 🔍 **Recommended Settings for LibreChat**

Based on your feedback, I recommend starting with these settings:

```yaml
env:
  TAVILY_API_KEY: "your-key"
  SEARCH_TIMEOUT: "120"      # 2 minutes
  CRAWL_TIMEOUT: "300"       # 5 minutes  
  MAX_SEARCH_RESULTS: "5"    # Reduce for faster processing
  CRAWL_MAX_DEPTH: "1"       # Keep shallow for speed
  CRAWL_LIMIT: "10"          # Moderate crawling
```

You can adjust these values based on your needs and hardware capabilities.

### 📚 **Documentation Updated**

The README now includes a comprehensive section on timeout and performance configuration with examples for different use cases.

Try the new version and let me know if this resolves your timeout issues! 🎯
